# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: util.proto for package 'util'

require 'grpc'
require 'util_pb'

module Util
  module Users
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'util.Users'

      # rpc XxXx (UsersRequest) returns (UsersListReply) {}
      rpc :List, ::Google::Protobuf::Empty, ::Util::UsersListReply
      rpc :Check, ::Util::UsersRequest, ::Util::UsersListReply
      rpc :Types, ::Util::ComplexRequest, ::Util::TypesReply
    end

    Stub = Service.rpc_stub_class
  end
end
